version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      
      - run:
          name: Run Tests
          command: mvn clean test
      
      - store_artifacts:
          path: target/reports
          destination: test-result

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
